FrontEnds/MultiShop.WebUI/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;

namespace MultiShop.WebUI.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.directory1 = "AnaSayfa";
            ViewBag.directory2 = "Ürünler";
            ViewBag.directory3 = "Ürün Listesi"; 
            return View();
        }
    }
}

FrontEnds/MultiShop.WebUI/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Mvc;
using MultiShop.WebUI.Services.BasketServices;
using MultiShop.WebUI.Services.DiscountServices;

namespace MultiShop.WebUI.Controllers
{
    public class DiscountController : Controller
    {
        private readonly IDiscountService _discountService;
        private readonly IBasketService _basketService;
        public DiscountController(IDiscountService discountService, IBasketService basketService)
        {
            _discountService = discountService;
            _basketService = basketService;
        }

        [HttpGet]
        public PartialViewResult ConfirmDiscountCoupon()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDiscountCoupon(string code)
        {
            var values = await _discountService.GetDiscountCouponCountRate(code);

            var basketValues = await _basketService.GetBasket();
            var totalPriceWithTax = basketValues.TotalPrice + basketValues.TotalPrice / 100 * 10;

            var totalNewPriceWithDiscount = totalPriceWithTax - (totalPriceWithTax / 100 * values);
            // ViewBag.totalNewPriceWithDiscount = totalNewPriceWithDiscount;

            return RedirectToAction("Index", "ShoppingCart", new { code = code, discountRate = values, totalNewPriceWithDiscount = totalNewPriceWithDiscount });
        }
    }
}

FrontEnds/MultiShop.WebUI/Views/Shared/Components/_ShoppingCardDiscountCouponComponentPartial/Default.cshtml
<div class="col-lg-4">
    <form method="post" class="mb-30" asp-controller="Discount" asp-action="ConfirmDiscountCoupon">
        <div class="input-group">
            <input type="text" class="form-control border-0 p-4" placeholder="Kupon Kodu">
            <div class="input-group-append">
                <button class="btn btn-primary">Kuponu Uygula</button>
            </div>
        </div>
    </form>
    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Sepet Özeti</span></h5>
    <div class="bg-light p-30 mb-5">
        <div class="border-bottom pb-2">
            <div class="d-flex justify-content-between mb-3">
                <h6>Toplam Ürün Fiyatı</h6>
                <h6>$150</h6>
            </div>
            <div class="d-flex justify-content-between">
                <h6 class="font-weight-medium">KDV</h6>
                <h6 class="font-weight-medium">$10</h6>
            </div>
        </div>
        <div class="pt-2">
            <div class="d-flex justify-content-between mt-2">
                <h5>Toplam</h5>
                <h5>$160</h5>
            </div>
            <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Ödeme Alanına İlerle</button>
        </div>
    </div>
</div>